---

- name: Install Required OS Packages
  package:
    name: cronie
    state: present

- name: build script
  copy:
    src: build_npm_config.sh
    dest: /usr/local/bin/
    mode: 0755

- name: install-npm-config-service
  copy:
    src: build_npm_config.service
    dest: /etc/systemd/system/build_npm_config.service

- name: build-npm-config-service
  systemd: 
    name: build_npm_config.service
    enabled: yes

- name: build-npm-config cron
  cron:
    name: build-npm-config
    user: root
    job: "/usr/local/bin/build_npm_config.sh &>> /var/log/build_npm_config.log"
    minute: "*/10"
    cron_file: build-npm-config

- name: add-region-variable
  cronvar:
    name: AWS_DEFAULT_REGION
    value: "eu-west-1"
    cron_file: build-npm-config

- name: add-env-varaible
  cronvar:
    name: JENKINS_ENV
    value: "%JENKINS_ENV%"
    cron_file: build-npm-config
