---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -x ANSIBLE0010 .
platforms:
  - name: instance
    image: amazonlinux:2
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    - lint
    - verify
verifier:
  name: testinfra
  options:
    hosts: 'docker://instance'
