---
dependency:
  name: galaxy
driver:
  name: docker
  lint: |
    set -e
    yamllint .
    ansible-lint .
    flake8
platforms:
  - name: instance
    image: fiercely/centos7:systemd
    privileged: True
    command: "/usr/sbin/init"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./molecule/default/config:/var/lib/jenkins/
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
